import Head from "next/head";

const Meta = () => {
  return (
    <Head>
      <title>Knock's Profile</title>
      <meta name="description" content="Generated by create next app" />
      <meta charSet="UTF-8" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    </Head>
  );
};

export default Meta;